---
- block:
  - name: Create root directory
    file:
      path: "{{ berachain_rootdir }}"
      state: directory
      mode: 0750
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Create config directory
    file:
      path: "{{ berachain_rootdir }}/config"
      state: directory
      mode: 0750
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Stage config.toml
    template:
      src: config.toml.j2
      dest: "{{ berachain_rootdir }}/config/config.toml"
      mode: 0644
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Stage app.toml
    template:
      src: app.toml.j2
      dest: "{{ berachain_rootdir }}/config/app.toml"
      mode: 0644
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Stage client.toml
    template:
      src: client.toml.j2
      dest: "{{ berachain_rootdir }}/config/client.toml"
      mode: 0644
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Get genesis.json
    get_url:
      url: "{{ berachain_genesis_url }}"
      dest: "{{ berachain_rootdir }}/config/genesis.json"
      mode: 0644
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"

  - name: Install berad service file
    template:
      src: berad.service.j2
      dest: "{{ berachain_systemd_dir }}/berad.service"
      owner: root
      group: root
      mode: 0755

  - name: Check if berachain_node_key is provided
    set_fact:
      node_key_provided: "{{ berachain_node_key is defined and berachain_node_key != '' }}"
    no_log: true

  - name: Stage node_key.json from template
    template:
      src: node_key.json.j2
      dest: "{{ berachain_rootdir }}/config/node_key.json"
      mode: 0600
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"
    when: node_key_provided
    no_log: true

  - name: Generate node_key.json
    command: "berad generate-key --output {{ berachain_rootdir }}/config/node_key.json"
    when: not node_key_provided
    become: true
    no_log: true
  become: true

- block:
  - name: Stage priv_validator_key.json
    template:
      src: priv_validator_key.json.j2
      dest: "{{ berachain_rootdir }}/config/priv_validator_key.json"
      mode: 0600
      owner: "{{ berachain_user_id }}"
      group: "{{ berachain_user_id }}"
    no_log: true
  when: berachain_role is 'validator'
  become: true
