---
- name: Download and Install berad
  get_url:
    url: "{{ berachain_bin_url }}"
    dest: "{{ berachain_bin_dir }}/berad"
    owner: "{{ berachain_user_id }}"
    group: "{{ berachain_user_id }}"
    mode: '0750'
  become: true
