---
#- name: Download and Install berad
#  get_url:
#    url: "{{ berachain_bin_url }}"
#    dest: "{{ berachain_bin_dir }}/berad"
#    owner: "{{ berachain_user_name }}"
#    group: "{{ berachain_group_name }}"
#    mode: '0755'
#  become: true

- name: (temp) Install berad from local bin
  copy:
    src: "bin/berad"
    dest: "{{ berachain_bin_dir }}/berad"
    owner: "{{ berachain_user_name }}"
    group: "{{ berachain_group_name }}"
    mode: '0755'
  become: true

- command: "{{ berachain_bin_dir }}/berad version"
  register: berad_version

- name: Log berad version
  debug:
    msg: "berad version is: {{ berad_version.stdout }}"
