---
- name: Install some useful packages
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
  - git
  - wget
  - jq
  - htop
  - sysstat
  - lsof
  - tmux

- name: Add bera user
  user:
    name: "{{ berachain_user_name }}"
    uid: "{{ berachain_user_id }}"
    system: true
    shell: /bin/false
  become: true
