---
- name: Install some useful packages
  package:
    name: "{{ item }}"
    state: latest
  become: true
  with_items:
  - git
  - wget
  - jq
  - htop
  - sysstat
  - lsof
  - tmux

- name: Check if user {{ berachain_user_name }} exists
  getent:
    database: passwd
    key: "{{ berachain_user_name }}"
  register: user_check

- name: "Add bera user - {{ berachain_user_name }}"
  user:
    name: "{{ berachain_user_name }}"
    uid: "{{ berachain_user_id }}"
    system: true
    shell: /bin/false
  become: true
  when:
    - berachain_user_name != 'root'
    - not user_check.ansible_facts.getent_passwd[berachain_user_name]

- meta: flush_handlers