---
- name: Update os (only if "--tags os-update" was applied)
  include_tasks: "{{ ansible_os_family | lower }}.yaml"

- include_tasks: common.yaml

- include_tasks: berad-install.yaml

- include_tasks: berad-config.yaml

- include_tasks: berad-run.yaml
