---
- name: OS specific config 
  include_tasks: "{{ ansible_os_family | lower }}.yaml"
  tags: os 
  
- name: Common config 
  include_tasks: common.yaml 

- include_tasks: polard-install.yaml

- include_tasks: polard-config.yaml

- include_tasks: polard-run.yaml
