---
- name: OS specific config
  include_tasks: "{{ ansible_os_family | lower }}.yaml"
  tags: os

- include_tasks: common.yaml

- include_tasks: berad-install.yaml

- include_tasks: berad-config.yaml

- include_tasks: berad-run.yaml
