---
- become: true
  block:
  - name: Ensure yum-utils is installed (for needs-restarting command)
    yum:
      name: yum-utils
      state: present

  - name: Perform a yum update
    yum:
      name: "*"
      state: latest

  - name: Determine if reboot is required
    shell: needs-restarting -r
    register: reboot_required
    ignore_errors: true
    changed_when: reboot_required.rc == 1
    notify: reboot

