---
name: CI Testing

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "${{ github.repository }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        env:
          ANSIBLE_FORCE_COLOR: '1'
