---
name: Lint
on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the codebase
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install test dependencies
      run: pip3 install yamllint
      shell: bash

    - name: Lint code
      run: yamllint .
      shell: bash
